version: "3.9"

services:
  backend:
    build:
      context: ./server
    container_name: avito-backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./client
    container_name: avito-frontend
    ports:
      - "3000:80"
    restart: always
